name: Build C++ and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    # Define o diretório de trabalho padrão para os passos de run:
    defaults:
      run:
        working-directory: sufficit-microsip

    outputs:
      version: ${{ steps.generate_version.outputs.VERSION }}

    steps:
    - name: 1. Checkout MicroSip Repository
      uses: actions/checkout@v4
      with:
        # Baixa seu projeto para uma pasta específica
        path: sufficit-microsip

    # ===================== PASSO NOVO E CRUCIAL =====================
    - name: 2. Clone PJSIP Repository
      uses: actions/checkout@v4
      with:
        # Clona o repositório oficial da PJSIP
        repository: pjsip/pjproject
        # Para uma pasta chamada 'pjproject' ao lado da sua
        path: pjproject
    # ==============================================================

    - name: 3. Generate Version Tag
      id: generate_version
      run: |
        $VERSION="v$(Get-Date -Format 'yyyy.MM.dd').${{ github.run_number }}"
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: 4. Add MSBuild to path
      uses: microsoft/setup-msbuild@v2
      
    - name: 5. Build the project
      run: msbuild.exe /p:Configuration=Release /p:Platform=x86 microsip.vcxproj

    - name: 6. Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: microsip-build
        # O caminho do artefato precisa ser ajustado pois estamos em um subdiretório
        path: sufficit-microsip/Release/microsip.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 1. Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: microsip-build

    - name: 2. Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.build.outputs.version }}
        name: "Release ${{ needs.build.outputs.version }}"
        body: |
          Versão compilada automaticamente a partir do último push para a branch main.
        files: microsip.exe