# =================================================================================================
# GitHub Actions Workflow: Compilação do MicroSIP no Windows com Opus
#
# Este fluxo de trabalho automatiza a compilação do projeto MicroSIP para Windows (x64),
# incorporando as bibliotecas Opus pré-compiladas e a própria biblioteca PJSIP.
#
# Assume-se que:
# - O script 'scripts/download_opus_windows.ps1' está presente no repositório.
# - A PJSIP é compilada a partir de 'sufficit/pjproject' dentro do workflow.
#
# Changes:
#   - Updated the `patch_microsip_vcxproj.ps1` call to include `PjsipAppsIncludePath` parameter.
#   - Ensured all paths are correctly defined and used.
#   - Removed redundant steps and clarified comments.
# =================================================================================================

name: Compilar MicroSIP no Windows (com Opus e PJSIP)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-microsip:
    name: Compilar MicroSIP no Windows
    runs-on: windows-latest

    steps:
      # Step 1: Checkout do repositório MicroSIP
      - name: Checkout do Repositório MicroSIP
        uses: actions/checkout@v4
        with:
          repository: sufficit/sufficit-microsip
          path: . # Checkout para a raiz do workspace
          submodules: recursive

      # Step 2: Checkout do repositório PJSIP
      - name: Checkout do Repositório PJSIP
        uses: actions/checkout@v4
        with:
          repository: sufficit/pjproject
          path: external/pjproject # Clonar PJSIP para external/pjproject

      # Step 3: Configurar MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64 # Garantir que o MSBuild para x64 está disponível

      # Step 4: Compilar PJSIP
      - name: Build PJSIP
        shell: pwsh
        run: |
          # Navegar para o diretório PJSIP
          Set-Location external/pjproject
          Write-Host "Caminho atual Set-Location: $(Get-Location)"

          # Descarregar e preparar bibliotecas Opus para PJSIP
          Write-Host "Executando scripts/download_opus_windows.ps1 para PJSIP..."
          # O script download_opus_windows.ps1 está na raiz do repositório principal (sufficit-microsip)
          # Por isso, o caminho deve ser relativo ao GITHUB_WORKSPACE
          & "$env:GITHUB_WORKSPACE/scripts/download_opus_windows.ps1"
          if ($LASTEXITCODE -ne 0) { exit 1 }
          Write-Host "Scripts/download_opus_windows.ps1 concluído."

          # Copiar ficheiros de configuração PJSIP
          Write-Host "Copiando config_site.h e pjsip_extra_defines.h para PJSIP..."
          Copy-Item -Path "$env:GITHUB_WORKSPACE/scripts/config_site_content.h" -Destination "pjlib/include/pj/config_site.h" -Force
          Copy-Item -Path "$env:GITHUB_WORKSPACE/scripts/pjsip_extra_defines_content.h" -Destination "pjlib/include/pj/pjsip_extra_defines.h" -Force
          Write-Host "Ficheiros de configuração PJSIP copiados."

          # Patch PJSIP pjmedia_codec.vcxproj para definições x64 e Opus
          Write-Host "Patching pjmedia_codec.vcxproj para PJSIP..."
          $pjmedia_codec_vcxproj_path = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "external/pjproject/pjmedia/build/pjmedia_codec.vcxproj"
          # O script patch.ps1 está na raiz do repositório principal (sufficit-microsip)
          & "$env:GITHUB_WORKSPACE/scripts/patch.ps1" -ProjFile $pjmedia_codec_vcxproj_path
          if ($LASTEXITCODE -ne 0) { exit 1 }
          Write-Host "pjmedia_codec.vcxproj patched."

          # Compilar a solução PJSIP
          Write-Host "Compilando solução PJSIP..."
          $pjSlnPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "external/pjproject/pjproject-vs14.sln"
          # O script build_pjsip.ps1 está na raiz do repositório principal (sufficit-microsip)
          & "$env:GITHUB_WORKSPACE/scripts/build_pjsip.ps1" -SlnFile $pjSlnPath
          if ($LASTEXITCODE -ne 0) {
              Write-Host "##[error]A compilação da solução PJSIP falhou."
              exit 1
          }
          Write-Host "scripts/build_pjsip.ps1 concluído com LASTEXITCODE: $LASTEXITCODE."
          Write-Host "Compilação PJSIP concluída."

          # Voltar para o diretório raiz do MicroSIP
          Set-Location $env:GITHUB_WORKSPACE
          Write-Host "Voltando ao diretório raiz do MicroSIP: $(Get-Location)"

      # Step 5: Aplicar patch ao ficheiro de projeto do MicroSIP
      - name: Aplicar patch ao projeto MicroSIP
        shell: pwsh
        run: |
          $microsipVcxprojPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "microsip.vcxproj"
          $pjsipIncludeRoot = "external/pjproject" # Relativo à raiz do MicroSIP (onde os módulos PJSIP estão)
          $pjsipLibPath = "external/pjproject/lib" # Relativo à raiz do MicroSIP (onde as libs PJSIP serão geradas)
          $pjsipAppsIncludePath = "external/pjproject/pjsip/include" # Caminho para pjsua.h

          Write-Host "Aplicando patch ao microsip.vcxproj em: $microsipVcxprojPath"
          Write-Host "PJSIP Include Root: $pjsipIncludeRoot"
          Write-Host "PJSIP Lib Path: $pjsipLibPath"
          Write-Host "PJSIP Apps Include Path: $pjsipAppsIncludePath"

          # Chamar o script de patch com todos os parâmetros necessários
          # O script patch_microsip_vcxproj.ps1 está na raiz do repositório principal (sufficit-microsip)
          & "$env:GITHUB_WORKSPACE/scripts/patch_microsip_vcxproj.ps1" `
            -ProjFile $microsipVcxprojPath `
            -PjsipIncludeRoot $pjsipIncludeRoot `
            -PjsipLibRoot $pjsipLibPath `
            -PjsipAppsIncludePath $pjsipAppsIncludePath
          if ($LASTEXITCODE -ne 0) { exit 1 }

      # Step 6: Compilar a solução MicroSIP (final)
      - name: Compilar Solução MicroSIP (Final)
        shell: pwsh
        run: |
          $microsipSlnPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "MicroSIP.sln"
          Write-Host "Compilando solução MicroSIP: $microsipSlnPath"
          msbuild.exe "$microsipSlnPath" /p:Configuration=Release /p:Platform=x64 /m /t:Build
          if ($LASTEXITCODE -ne 0) {
              Write-Host "##[error]A compilação do MicroSIP falhou com o código de saída $LASTEXITCODE."
              exit 1
          }
          Write-Host "Compilação do MicroSIP concluída com sucesso."

      # Step 7: Opcional: Upload de artefatos da compilação do MicroSIP
      - name: Upload de Binários do MicroSIP
        uses: actions/upload-artifact@v4
        with:
          name: microsip-windows-x64-binarios
          path: |
            MicroSIP\x64\Release\MicroSIP.exe
            MicroSIP\x64\Release\*.dll
            MicroSIP\x64\Release\*.lib
            # Adicione outros arquivos importantes se necessário, ex: pjsip.dll se for dynamic build
