name: Build C++ and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.generate_version.outputs.VERSION }}

    steps:
    - name: 1. Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        # ===================== LINHA ADICIONADA =====================
        # Esta opção garante que os submódulos do Git (como pjsip) sejam baixados.
        submodules: 'recursive'
        # ==========================================================

    - name: 2. Generate Version Tag
      id: generate_version
      run: |
        $VERSION="v$(Get-Date -Format 'yyyy.MM.dd').${{ github.run_number }}"
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: 3. Add MSBuild to path
      uses: microsoft/setup-msbuild@v2
      
    - name: 4. Build the project
      run: msbuild.exe /p:Configuration=Release /p:Platform=x86 microsip.vcxproj

    - name: 5. Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: microsip-build
        path: Release/microsip.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 1. Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: microsip-build

    - name: 2. Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.build.outputs.version }}
        name: "Release ${{ needs.build.outputs.version }}"
        body: |
          Versão compilada automaticamente a partir do último push para a branch main.
        files: microsip.exe