# =================================================================================================
# GITHUB ACTIONS WORKFLOW FOR BUILDING THE SUFFICIT/SUFFICIT-MICROSIP PROJECT
#
# WORKFLOW VERSION: 17 (Final Path Correction)
#
# Author: Hugo Castro de Deco, Sufficit
# Collaboration: Gemini AI for Google
# Date: June 12, 2025
#
# == Logic and Execution Steps (Final Reviewed Version) ==
#
# This workflow relies on `config_site.h` and `patch.ps1` existing in the repository root.
# It corrects the pathing issue from v16 where the scripts could not be found.
#
# 1.  **Setup (Steps 1-3):** Standard checkout.
# 2.  **Restructure (Step 4):** Moves PJSIP sources to the root.
# 3.  **Prepare & Patch (Step 5):** Copies the config and patch scripts from the checked-out
#     repository into their required locations and then executes the patch. This is the key fix.
# 4.  **Build & Finalize (Steps 6-13):** The rest of the workflow proceeds as planned.
# =================================================================================================

name: Build C++ and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.generate_version.outputs.VERSION }}

    steps:
    - name: 1. Checkout MicroSip Repository & Scripts
      uses: actions/checkout@v4
      with:
        repository: sufficit/sufficit-microsip
        path: sufficit-microsip

    - name: 2. Clone PJSIP Repository
      uses: actions/checkout@v4
      with:
        repository: pjsip/pjproject
        path: pjproject
    
    - name: 3. Clone Opus into PJSIP third_party
      uses: actions/checkout@v4
      with:
        repository: xiph/opus
        path: pjproject/third_party/opus

    - name: 4. Restructure PJSIP directories
      shell: pwsh
      run: |
        Move-Item -Path ${{ github.workspace }}/pjproject/* -Destination ${{ github.workspace }}/
        Remove-Item -Path ${{ github.workspace }}/pjproject -Recurse -Force

    - name: 5. Prepare and Execute PJSIP Patch
      shell: pwsh
      run: |
        echo "Copying config and patch files..."
        Copy-Item -Path sufficit-microsip/config_site.h -Destination pjlib/include/pj/ -Force
        Copy-Item -Path sufficit-microsip/patch.ps1 -Destination ./ -Force
        
        echo "Executing patch script..."
        ./patch.ps1
        
    - name: 6. Add MSBuild to path
      uses: microsoft/setup-msbuild@v2

    - name: 7. Build Entire PJSIP Solution
      shell: pwsh
      run: |
        echo "Building the entire PJSIP solution (pjproject-vs14.sln)..."
        msbuild.exe pjproject-vs14.sln /p:Configuration=Release /p:Platform=Win32

    - name: 8. Prepare Libraries for Final Build
      shell: pwsh
      run: |
        echo "--- Preparing all required libraries for MicroSIP ---"
        $microsip_lib_dir = "sufficit-microsip/lib"
        $microsip_opus_dir = "sufficit-microsip/third_party/opus/Win32"
        New-Item -ItemType Directory -Force -Path $microsip_lib_dir
        New-Item -ItemType Directory -Force -Path $microsip_opus_dir
        
        $opus_source_file = Get-Item "third_party/lib/libopus-*.lib"
        Copy-Item -Path $opus_source_file.FullName -Destination "$microsip_opus_dir/opus.lib" -Force
        $opus_name = $opus_source_file.Name
        echo "Copied $opus_name to $microsip_opus_dir/opus.lib"

        $pjlib_source = Get-Item "lib/libpjproject-i386-Win32-vc14-Release.lib"
        $pjlib_expected_name = "libpjproject-i386-Win32-vc14-Release-Static.lib"
        $pjlib_dest_renamed = "$microsip_lib_dir/$pjlib_expected_name"
        Copy-Item -Path $pjlib_source.FullName -Destination $pjlib_dest_renamed -Force
        $pjlib_name = $pjlib_source.Name
        echo "Copied and Renamed $pjlib_name to $pjlib_dest_renamed"

    - name: 9. Generate Version Tag
      id: generate_version
      working-directory: ./sufficit-microsip
      run: |
        $VERSION="v$(Get-Date -Format 'yyyy.MM.dd').${{ github.run_number }}"
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
    - name: 10. Build the final project
      working-directory: ./sufficit-microsip
      run: msbuild.exe /p:Configuration=Release /p:Platform=x86 microsip.vcxproj

    - name: 11. Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: microsip-build
        path: sufficit-microsip/Release/microsip.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 1. Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: microsip-build

    - name: 2. Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.build.outputs.version }}
        name: "Release ${{ needs.build.outputs.version }}"
        body: |
          Versão compilada automaticamente a partir do último push para a branch main.
        files: microsip.exe