# =================================================================================================
# GITHUB ACTIONS WORKFLOW FOR BUILDING THE SUFFICIT/SUFFICIT-MICROSIP PROJECT
#
# WORKFLOW VERSION: 20 (Definitive Fix - Copy-Item instead of Move-Item)
#
# Author: Hugo Castro de Deco, Sufficit
# Collaboration: Gemini AI for Google
# Date: June 13, 2025
#
# == Logic and Execution Steps ==
#
# This workflow uses the user-preferred external script method.
# It fixes all previous errors by using `Copy-Item` to merge the PJSIP directory
# into the workspace root, which avoids all file/directory conflicts.
# =================================================================================================

name: Build C++ and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.generate_version.outputs.VERSION }}

    steps:
    - name: 1. Checkout Main Repo & Scripts
      uses: actions/checkout@v4

    - name: 2. Prepare Dependencies and Patch
      shell: pwsh
      run: |
        echo "Cloning PJSIP..."
        git clone --depth 1 https://github.com/pjsip/pjproject.git
        
        echo "Cloning Opus..."
        git clone --depth 1 https://github.com/xiph/opus.git ./pjproject/third_party/opus

        echo "Merging PJSIP files into workspace root..."
        # THE FIX: Use Copy-Item to merge directories instead of Move-Item, avoiding conflicts.
        Copy-Item -Path ./pjproject/* -Destination ./ -Recurse -Force
        Copy-Item -Path ./pjproject/.* -Destination ./ -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Path ./pjproject -Recurse -Force
        
        echo "Copying config file and executing patch script..."
        Copy-Item -Path ./config_site.h -Destination ./pjlib/include/pj/ -Force
        ./patch.ps1
        
    - name: 3. Add MSBuild to path
      uses: microsoft/setup-msbuild@v2

    - name: 4. Build Entire PJSIP Solution
      shell: pwsh
      run: |
        echo "Building the entire PJSIP solution..."
        msbuild.exe pjproject-vs14.sln /p:Configuration=Release /p:Platform=Win32

    - name: 5. Prepare Libraries for Final Build
      shell: pwsh
      run: |
        echo "--- Preparing all required libraries for MicroSIP ---"
        $microsip_lib_dir = "./lib"
        $microsip_opus_dir = "./third_party/opus/Win32"
        New-Item -ItemType Directory -Force -Path $microsip_lib_dir
        New-Item -ItemType Directory -Force -Path $microsip_opus_dir
        
        $opus_source_file = Get-Item "third_party/lib/libopus-*.lib"
        Copy-Item -Path $opus_source_file.FullName -Destination "$microsip_opus_dir/opus.lib" -Force
        
        $pjlib_source = Get-Item "lib/libpjproject-i386-Win32-vc14-Release.lib"
        $pjlib_dest_renamed = "$microsip_lib_dir/libpjproject-i386-Win32-vc14-Release-Static.lib"
        Copy-Item -Path $pjlib_source.FullName -Destination $pjlib_dest_renamed -Force
        
        Write-Host "Library collection successful."
        
    - name: 6. Generate Version Tag
      id: generate_version
      run: |
        <span class="math-inline">VERSION\="v</span>(Get-Date -Format 'yyyy.MM.dd').${{ github