# =================================================================================================
# GitHub Actions Workflow: Compilação do MicroSIP no Windows com Opus
#
# Este fluxo de trabalho automatiza a compilação do projeto MicroSIP para Windows (x64),
# incorporando as bibliotecas Opus pré-compiladas e a própria biblioteca PJSIP.
#
# Assume-se que:
# - O script 'scripts/download_opus_windows.ps1' está presente no repositório.
# - A PJSIP é compilada a partir de 'sufficit/pjproject' dentro do workflow.
# =================================================================================================

name: Compilar MicroSIP no Windows (com Opus e PJSIP)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-microsip:
    name: Compilar MicroSIP no Windows
    runs-on: windows-latest

    steps:
      # Step 1: Checkout do repositório MicroSIP
      - name: Checkout do Repositório MicroSIP
        uses: actions/checkout@v4
        with:
          repository: sufficit/sufficit-microsip
          path: . # Checkout para a raiz do workspace
          submodules: recursive

      # Step 2: Checkout do repositório PJSIP
      - name: Checkout do Repositório PJSIP
        uses: actions/checkout@v4
        with:
          repository: sufficit/pjproject
          path: external/pjproject # Checkout PJSIP para um subdiretório
          submodules: recursive

      # Step 3: Adicionar MSBuild ao PATH do ambiente
      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2
        with:
          # Para garantir que o MSBuild para x64 é usado
          msbuild-architecture: x64


      # Step 4: Preparar e Compilar PJSIP
      - name: Preparar e Compilar PJSIP
        shell: pwsh
        run: |
          # Navegar para o diretório PJSIP
          Set-Location external/pjproject
          Write-Host "Caminho atual Set-Location: $(Get-Location)"

          # Descarregar e preparar bibliotecas Opus para PJSIP
          Write-Host "Executando scripts/download_opus_windows.ps1 para PJSIP..."
          scripts/download_opus_windows.ps1
          Write-Host "Scripts/download_opus_windows.ps1 concluído."

          # Copiar ficheiros de configuração PJSIP
          Write-Host "Copiando config_site.h e pjsip_extra_defines.h para PJSIP..."
          Copy-Item -Path "scripts/config_site_content.h" -Destination "pjlib/include/pj/config_site.h" -Force
          Copy-Item -Path "scripts/pjsip_extra_defines_content.h" -Destination "pjlib/include/pj/pjsip_extra_defines.h" -Force
          Write-Host "Ficheiros de configuração PJSIP copiados."

          # Patch PJSIP pjmedia_codec.vcxproj para definições x64 e Opus
          Write-Host "Patching pjmedia_codec.vcxproj para PJSIP..."
          $pjmedia_codec_vcxproj_path = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "external/pjproject/pjmedia/build/pjmedia_codec.vcxproj"
          scripts/patch.ps1 -ProjFile $pjmedia_codec_vcxproj_path
          Write-Host "pjmedia_codec.vcxproj patched."

          # Compilar a solução PJSIP
          Write-Host "Compilando solução PJSIP..."
          $pjSlnPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "external/pjproject/pjproject-vs14.sln"
          scripts/build_pjsip.ps1 -SlnFile $pjSlnPath
          Write-Host "scripts/build_pjsip.ps1 concluído com LASTEXITCODE: $LASTEXITCODE."
          if ($LASTEXITCODE -ne 0) {
              Write-Host "##[error]A compilação da solução PJSIP falhou."
              exit 1
          }
          Write-Host "Compilação PJSIP concluída."

          # --- DEBUG: Listar conteúdo COMPLETO da pasta external/pjproject após compilação PJSIP ---
          Write-Host "--- DEBUG: Conteúdo COMPLETO de external/pjproject/ após compilação PJSIP ---"
          Get-ChildItem -Path "." -Recurse | Select-Object FullName
          Write-Host "-----------------------------------------------------------------------------------"
          # ------------------------------------------------------------------------------------------

          # Voltar para o diretório raiz do MicroSIP
          Set-Location $env:GITHUB_WORKSPACE
          Write-Host "Voltando ao diretório raiz do MicroSIP: $(Get-Location)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Copiar componentes PJSIP compilados para o MicroSIP
      - name: Copiar Componentes PJSIP para MicroSIP
        shell: pwsh
        run: |
          $pjsipSourceDir = "external/pjproject"
          $microsipPjLibDir = "lib/pjproject" # Novo diretório para as libs do PJSIP dentro do MicroSIP
          New-Item -ItemType Directory -Path $microsipPjLibDir -Force
          Write-Host "Criado diretório de destino PJSIP para MicroSIP: $microsipPjLibDir"

          Write-Host "Copiando bibliotecas PJSIP (.lib) para MicroSIP..."
          # Copia todos os .lib da pasta 'lib' do PJSIP para a nova pasta 'lib/pjproject' do MicroSIP
          Copy-Item -Path "$pjsipSourceDir/lib/*.lib" -Destination "$microsipPjLibDir/" -Force
          Write-Host "Bibliotecas PJSIP .lib copiadas."

          Write-Host "Copiando ficheiros de inclusão PJSIP para MicroSIP..."
          # Copia as pastas de inclusão de cada módulo PJSIP
          Copy-Item -Recurse -Path "$pjsipSourceDir/pjlib/include" -Destination "$microsipPjLibDir/pjlib/include" -Force
          Copy-Item -Recurse -Path "$pjsipSourceDir/pjlib-util/include" -Destination "$microsipPjLibDir/pjlib-util/include" -Force
          Copy-Item -Recurse -Path "$pjsipSourceDir/pjnath/include" -Destination "$microsipPjLibDir/pjnath/include" -Force
          Copy-Item -Recurse -Path "$pjsipSourceDir/pjmedia/include" -Destination "$microsipPjLibDir/pjmedia/include" -Force
          Copy-Item -Recurse -Path "$pjsipSourceDir/pjsip/include" -Destination "$microsipPjLibDir/pjsip/include" -Force
          # A linha anterior que tentava copiar pjsip-apps/include foi REMOVIDA.
          # O pjsua.h está localizado dentro de pjsip/include/pjsua-lib/, que já será copiado acima.

          Write-Host "Ficheiros de inclusão PJSIP copiados."

          Write-Host "Componentes PJSIP copiados para $microsipPjLibDir."

          # --- DEBUG: Listar conteúdo da pasta de inclusão pjsip-apps/include do MicroSIP após cópia ---
          # Esta pasta pode não existir se o pjsua.h estiver diretamente em pjsip/include/.
          # Usamos -ErrorAction SilentlyContinue para evitar falha se a pasta não for criada.
          Write-Host "--- DEBUG: Conteúdo de lib/pjproject/pjsip/include/pjsua-lib/ após cópia para MicroSIP ---"
          Get-ChildItem -Path "$microsipPjLibDir/pjsip/include/pjsua-lib" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName
          Write-Host "--------------------------------------------------------------------------------"
          # ------------------------------------------------------------------------------------------

      # Step 6: Patch microsip.vcxproj para incluir PJSIP paths
      # O script 'patch_microsip_vcxproj.ps1' é assumido como existente na pasta 'scripts/'
      - name: Patch microsip.vcxproj para PJSIP
        shell: pwsh
        run: |
          $microsipVcxprojPath = "microsip.vcxproj" # Caminho do .vcxproj do MicroSIP
          $pjsipLibPath = "lib/pjproject" # Caminho relativo da PJSIP para as libs
          $pjsipIncludeRoot = "lib/pjproject" # Caminho relativo da PJSIP para os includes (raiz da estrutura copiada)

          $patchMicrosipScriptPath = "scripts/patch_microsip_vcxproj.ps1"

          Write-Host "Executando $patchMicrosipScriptPath em $microsipVcxprojPath"
          # Adicione o caminho específico para o pjsua.h que está em pjsip/include,
          # e não pjsip-apps/include que não existe.
          # Passamos o caminho onde o pjsua.h está realmente (lib/pjproject/pjsip/include)
          & $patchMicrosipScriptPath -ProjFile $microsipVcxprojPath `
              -PjsipIncludeRoot $pjsipIncludeRoot `
              -PjsipLibRoot $pjsipLibPath `
              -PjsipAppsIncludePath (Join-Path -Path $pjsipIncludeRoot -ChildPath "pjsip/include") # Usando este como o caminho de inclusão da pjsua-lib

          Write-Host "Patch microsip.vcxproj concluído."

      # Step 7: Compilar a solução MicroSIP (final)
      - name: Compilar Solução MicroSIP (Final)
        shell: pwsh
        run: |
          # O caminho da solução deve ser relativo à raiz do workspace, pois estamos de volta à raiz
          $microsipSlnPath = "MicroSIP.sln" # Assumindo que MicroSIP.sln está na raiz do repositório
          Write-Host "Compilando solução MicroSIP: $microsipSlnPath"
          msbuild.exe "$microsipSlnPath" /p:Configuration=Release /p:Platform=x64 /m /t:Build
          if ($LASTEXITCODE -ne 0) {
              Write-Host "##[error]A compilação do MicroSIP falhou com o código de saída $LASTEXITCODE."
              exit 1
          }
          Write-Host "Compilação do MicroSIP concluída com sucesso."

      # Step 8: Opcional: Upload de artefatos da compilação do MicroSIP
      - name: Upload de Binários do MicroSIP
        uses: actions/upload-artifact@v4
        with:
          name: microsip-windows-x64-binarios
          path: |
            bin/Release/*.exe # Exemplo: Ajuste para o caminho onde os executáveis do MicroSIP são gerados
            bin/Release/*.dll
            lib/pjproject/*.lib # libs PJSIP copiadas para aqui
            # Adicione outros arquivos importantes, se necessário
          retention-days: 7
