# =================================================================================================
# GITHUB ACTIONS WORKFLOW FOR BUILDING THE SUFFICIT/SUFFICIT-MICROSIP PROJECT
#
# Author: Gemini AI for Google
# Date: June 12, 2025
#
# == Workflow Logic and Execution Steps ==
#
# This workflow automates the build of the MicroSIP C++ project from source, including its key
# dependencies. Each step is designed to correctly prepare the environment for a successful build.
#
# 1.  **Checkout Repositories:**
#     - Checks out the main `sufficit-microsip` project and the `pjsip/pjproject` dependency
#       into a parallel directory structure, as required by the build system.
#
# 2.  **Prepare PJSIP Source:**
#     - Step 3 (`Restructure PJSIP directories`): Moves the PJSIP source files to the workspace
#       root to match the project's hardcoded include paths (e.g., `..\pjlib`, `..\pjsip`).
#     - Step 4 (`Create PJSIP config_site.h`): Generates the mandatory PJSIP configuration file
#       `pjlib/include/pj/config_site.h` with the specific feature macros required by MicroSIP.
#
# 3.  **Build Dependencies from Source:**
#     - Third-party libraries are built from source to ensure compatibility.
#     - Step 5 (`Build PJSIP Libraries`): Compiles the entire PJSIP solution. This creates the main
#       `libpjproject...lib` file needed by the linker.
#     - Step 6 (`Build Opus Dependency`): Clones and compiles the Opus audio codec, producing `opus.lib`.
#     - Step 7 (`Copy Opus library...`): Copies the compiled `opus.lib` into the
#       `third_party/opus/Win32/` directory, where the linker is configured to look for it.
#
# 4.  **Build and Release the Main Project:**
#     - The final steps set up the build environment, run the MSBuild command for the main project,
#       upload the resulting .exe as an artifact, and create a GitHub Release.
# =================================================================================================

name: Build C++ and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.generate_version.outputs.VERSION }}

    steps:
    - name: 1. Checkout MicroSip Repository
      uses: actions/checkout@v4
      with:
        path: sufficit-microsip

    - name: 2. Clone PJSIP Repository
      uses: actions/checkout@v4
      with:
        repository: pjsip/pjproject
        path: pjproject

    - name: 3. Restructure PJSIP directories
      shell: pwsh
      run: |
        Move-Item -Path ${{ github.workspace }}\pjproject\* -Destination ${{ github.workspace }}\
        Remove-Item -Path ${{ github.workspace }}\pjproject -Recurse -Force

    - name: 4. Create PJSIP config_site.h
      shell: pwsh
      run: |
        $config = @"
        #define PJ_WIN32 1
        #include <windows.h>
        #define PJ_HAS_IPV6 1
        #define PJSUA_MAX_ACC 10
        #define PJSUA_MAX_CALLS 32
        #define PJMEDIA_HAS_G729_CODEC 1
        #define PJMEDIA_HAS_ILBC_CODEC 1
        #define PJMEDIA_HAS_SPEEX_CODEC 1
        #define PJMEDIA_HAS_SPEEX_AEC 1
        #define PJMEDIA_HAS_OPUS_CODEC 1
        #define PJMEDIA_HAS_VIDEO 0
        #define PJMEDIA_VIDEO_DEV_HAS_SDL 0
        #define PJMEDIA_VIDEO_DEV_HAS_DSHOW 0
        #define PJ_LOG_MAX_LEVEL 3
        #define PJMEDIA_AUD_MAX_DEVS 64
        "@
        Set-Content -Path "${{ github.workspace }}\pjlib\include\pj\config_site.h" -Value $config

    # ===================== NOVO PASSO PARA COMPILAR A PJSIP =====================
    - name: 5. Build PJSIP Libraries
      shell: pwsh
      run: |
        echo "Building PJSIP solution..."
        # Build the VS 2015 solution file; MSBuild will auto-upgrade it.
        # The output libraries will be placed in the various `lib` folders inside the PJSIP folders.
        msbuild.exe pjproject-vs14.sln /p:Configuration=Release /p:Platform=Win32
    # ==========================================================================

    - name: 6. Build Opus Dependency
      shell: pwsh
      run: |
        git clone --depth 1 https://github.com/xiph/opus.git opus-source
        cmake -S opus-source -B opus-build -G "Visual Studio 17 2022" -A Win32
        cmake --build opus-build --config Release

    - name: 7. Copy Opus library to expected location
      shell: pwsh
      run: |
        $dest_dir = "third_party/opus/Win32"
        New-Item -ItemType Directory -Force -Path $dest_dir
        Copy-Item -Path "opus-build/Release/opus.lib" -Destination $dest_dir

    - name: 8. Generate Version Tag
      id: generate_version
      working-directory: ./sufficit-microsip
      run: |
        $VERSION="v$(Get-Date -Format 'yyyy.MM.dd').${{ github.run_number }}"
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: 9. Add MSBuild to path
      uses: microsoft/setup-msbuild@v2
      
    - name: 10. Build the project
      working-directory: ./sufficit-microsip
      run: msbuild.exe /p:Configuration=Release /p:Platform=x86 microsip.vcxproj

    - name: 11. Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: microsip-build
        path: sufficit-microsip/Release/microsip.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 1. Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: microsip-build

    - name: 2. Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.build.outputs.version }}
        name: "Release ${{ needs.build.outputs.version }}"
        body: |
          Versão compilada automaticamente a partir do último push para a branch main.
        files: microsip.exe