# =================================================================================================
# GITHUB ACTIONS WORKFLOW FOR BUILDING THE SUFFICIT/SUFFICIT-MICROSIP PROJECT
#
# WORKFLOW VERSION: 8
#
# Author: Hugo Castro de Deco, Sufficit
# Collaboration: Gemini AI for Google
# Date: June 12, 2025
#
# == Logic and Execution Steps (Validated up to this version) ==
#
# 1.  **Checkout & Structure (Steps 1-4):** All source codes are checked out, with Opus's source
#     placed inside PJSIP's `third_party` directory. PJSIP is moved to the workspace root.
# 2.  **Configuration (Step 5):** The mandatory `pjlib/include/pj/config_site.h` is created.
#
# == Objective of This Version ==
#
# 3.  **Patch PJSIP Project File (Step 6):** The script in the previous version had a YAML syntax
#     error. This version uses a rewritten, YAML-safe PowerShell script to correctly modify
#     the `pjmedia-codec.vcxproj` file, adding the required include path for the Opus headers.
#
# 4.  **Unified PJSIP Build (Step 8):** With the project file successfully patched, this step
#     will build the entire PJSIP solution. A full success is now expected.
# =================================================================================================

name: Build C++ and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.generate_version.outputs.VERSION }}

    steps:
    - name: 1. Checkout MicroSip Repository
      uses: actions/checkout@v4
      with:
        repository: sufficit/sufficit-microsip
        path: sufficit-microsip

    - name: 2. Clone PJSIP Repository
      uses: actions/checkout@v4
      with:
        repository: pjsip/pjproject
        path: pjproject
    
    - name: 3. Clone Opus into PJSIP third_party
      uses: actions/checkout@v4
      with:
        repository: xiph/opus
        path: pjproject/third_party/opus

    - name: 4. Restructure PJSIP directories
      shell: pwsh
      run: |
        Move-Item -Path ${{ github.workspace }}\pjproject\* -Destination ${{ github.workspace }}\
        Remove-Item -Path ${{ github.workspace }}\pjproject -Recurse -Force

    - name: 5. Create PJSIP config_site.h
      shell: pwsh
      run: |
        $config = @"
        #define PJ_WIN32 1
        #include <windows.h>
        #define PJ_HAS_IPV6 1
        #define PJSUA_MAX_ACC 10
        #define PJSUA_MAX_CALLS 32
        #define PJMEDIA_HAS_G729_CODEC 1
        #define PJMEDIA_HAS_ILBC_CODEC 1
        #define PJMEDIA_HAS_SPEEX_CODEC 1
        #define PJMEDIA_HAS_SPEEX_AEC 1
        #define PJMEDIA_HAS_OPUS_CODEC 1
        #define PJMEDIA_HAS_VIDEO 0
        #define PJMEDIA_VIDEO_DEV_HAS_SDL 0
        #define PJMEDIA_VIDEO_DEV_HAS_DSHOW 0
        #define PJ_LOG_MAX_LEVEL 3
        #define PJMEDIA_AUD_MAX_DEVS 64
        "@
        Set-Content -Path "${{ github.workspace }}\pjlib\include\pj\config_site.h" -Value $config

    - name: 6. Patch pjmedia-codec.vcxproj to add Opus include path
      shell: pwsh
      run: |
        $projFile = "pjmedia/build/pjmedia_codec.vcxproj"
        echo "Loading project file: $projFile"
        $xml = [xml](Get-Content $projFile)
        $targetCondition = "'$(Configuration)|$(Platform)'=='Release|Win32'"
        $patched = $false

        foreach ($group in $xml.Project.ItemDefinitionGroup) {
            if ($group.Condition -eq $targetCondition) {
                echo "Found matching configuration. Patching..."
                $includeDirsNode = $group.ClCompile.AdditionalIncludeDirectories
                $currentIncludes = $includeDirsNode.'#text'
                $newIncludes = $currentIncludes + ";../../third_party/opus/include"
                $includeDirsNode.'#text' = $newIncludes
                echo "Successfully patched include path."
                $patched = $true
                break
            }
        }

        if (-not $patched) {
            echo "ERROR: Could not find 'Release|Win32' configuration in $projFile"
            exit 1
        }
        
        $xml.Save($projFile)
        echo "Saved updated project file: $projFile"
        
    - name: 7. Add MSBuild to path
      uses: microsoft/setup-msbuild@v2

    - name: 8. Build PJSIP and ALL its Dependencies
      shell: pwsh
      run: |
        echo "Building the entire PJSIP solution..."
        msbuild.exe pjproject-vs14.sln /p:Configuration=Release /p:Platform=Win32

    - name: 9. Copy all required libraries for MicroSIP
      shell: pwsh
      run: |
        echo "Copying PJSIP libraries..."
        Copy-Item -Path lib/libpjproject-*.lib -Destination sufficit-microsip/lib/ -ErrorAction SilentlyContinue
        
        echo "Copying third-party libraries built by PJSIP..."
        $dest_dir = "sufficit-microsip/third_party/lib"
        New-Item -ItemType Directory -Force -Path $dest_dir
        Copy-Item -Path third_party/lib/*.lib -Destination $dest_dir -ErrorAction SilentlyContinue
        
        echo "Copying Opus library to its specific folder..."
        $opus_dir = "sufficit-microsip/third_party/opus/Win32"
        New-Item -ItemType Directory -Force -Path $opus_dir
        Copy-Item -Path third_party/lib/libopus-*.lib -Destination "$opus_dir/opus.lib" -ErrorAction SilentlyContinue

    - name: 10. Generate Version Tag
      id: generate_version
      working-directory: ./sufficit-microsip
      run: |
        $VERSION="v$(Get-Date -Format 'yyyy.MM.dd').${{ github.run_number }}"
        echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      
    - name: 11. Build the final project
      working-directory: ./sufficit-microsip
      run: msbuild.exe /p:Configuration=Release /p:Platform=x86 microsip.vcxproj

    - name: 12. Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: microsip-build
        path: sufficit-microsip/Release/microsip.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: 1. Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: microsip-build

    - name: 2. Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.build.outputs.version }}
        name: "Release ${{ needs.build.outputs.version }}"
        body: |
          Versão compilada automaticamente a partir do último push para a branch main.
        files: microsip.exe